"""Read real metadata out of the published PDFs.

Run: python scripts/docmeta.py            # print
     python scripts/docmeta.py --write    # update src/data/docmeta.ts

Size, page count and file date come from the files themselves, so a parent sees
what they are about to download — a 2.2 MB handbook on mobile data is worth
warning about — and the numbers cannot drift from reality by being typed twice.

One caution that the UI has to carry: a PDF's CreationDate/ModDate is when the
*file* was written, not when the *policy* changed. Someone re-saving a document
to fix a typo moves the date without changing a word of the content. The site
therefore says "file dated", never "updated" or "last reviewed" — the second
would be a claim about Tiny Stars' process that nobody has published.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PDF_DIR = ROOT / "public" / "assets" / "pdf"
TARGET = ROOT / "src" / "data" / "docmeta.ts"

MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
          'July', 'August', 'September', 'October', 'November', 'December']


def read(path: Path) -> dict:
    raw = path.read_bytes()

    # Page objects are `/Type /Page` — the trailing character guard keeps this
    # from also matching `/Type /Pages`, the tree root.
    pages = len(re.findall(rb"/Type\s*/Page[^s]", raw))

    # Newer PDFs put the page tree inside compressed object streams, where this
    # scan finds nothing. Reporting no count is correct; guessing one is not.
    dates = sorted({d.decode() for d in re.findall(rb"/(?:CreationDate|ModDate)\s*\(D:(\d{8})", raw)})
    latest = dates[-1] if dates else None

    pretty = None
    if latest:
        y, m, d = latest[:4], int(latest[4:6]), int(latest[6:8])
        if 1 <= m <= 12:
            pretty = f"{d} {MONTHS[m - 1]} {y}"

    return {
        "slug": path.stem,
        "bytes": len(raw),
        "size": f"{len(raw) / 1_048_576:.1f} MB" if len(raw) >= 1_048_576 else f"{round(len(raw) / 1024)} KB",
        "pages": pages or None,
        "fileDate": pretty,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    if not PDF_DIR.exists():
        print("no public/assets/pdf")
        return 1

    meta = [read(p) for p in sorted(PDF_DIR.glob("*.pdf"))]
    for m in meta:
        print(f"  {m['slug']:<30} {m['size']:>8}  "
              f"{str(m['pages']) + ' page(s)' if m['pages'] else 'pages unknown':<14} {m['fileDate'] or 'no date'}")

    if not args.write:
        print("\n(pass --write to update src/data/docmeta.ts)")
        return 0

    body = ",\n".join(
        "  {\n"
        f"    slug: '{m['slug']}',\n"
        f"    size: '{m['size']}',\n"
        f"    pages: {m['pages'] if m['pages'] else 'null'},\n"
        f"    fileDate: {repr(m['fileDate']).replace(chr(39), chr(39)) if m['fileDate'] else 'null'},\n"
        "  }"
        for m in meta
    )
    TARGET.write_text(
        "/**\n"
        " * Generated by `python scripts/docmeta.py --write`. Do not edit by hand.\n"
        " *\n"
        " * `fileDate` is the PDF's own CreationDate/ModDate — when the file was\n"
        " * written, which is not the same as when the policy changed. The UI says\n"
        " * \"file dated\" for exactly that reason: \"last updated\" would be a claim\n"
        " * about Tiny Stars' review process that nobody has published.\n"
        " *\n"
        " * `pages` is null where the page tree sits inside a compressed object\n"
        " * stream and cannot be counted without a full parser. Null renders as\n"
        " * nothing rather than as a guess.\n"
        " */\n\n"
        "export interface DocMeta {\n"
        "  slug: string;\n"
        "  size: string;\n"
        "  pages: number | null;\n"
        "  fileDate: string | null;\n"
        "}\n\n"
        "export const docMeta: DocMeta[] = [\n" + body + ",\n];\n\n"
        "export const metaFor = (slug: string): DocMeta | undefined =>\n"
        "  docMeta.find((d) => d.slug === slug);\n",
        encoding="utf-8",
    )
    print(f"\nwrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
