/**
 * Generated by `python scripts/docmeta.py --write`. Do not edit by hand.
 *
 * `fileDate` is the PDF's own CreationDate/ModDate — when the file was
 * written, which is not the same as when the policy changed. The UI says
 * "file dated" for exactly that reason: "last updated" would be a claim
 * about Tiny Stars' review process that nobody has published.
 *
 * `pages` is null where the page tree sits inside a compressed object
 * stream and cannot be counted without a full parser. Null renders as
 * nothing rather than as a guess.
 */

export interface DocMeta {
  slug: string;
  size: string;
  pages: number | null;
  fileDate: string | null;
}

export const docMeta: DocMeta[] = [
  {
    slug: 'classroom-routine',
    size: '119 KB',
    pages: 4,
    fileDate: '18 April 2026',
  },
  {
    slug: 'parent-handbook',
    size: '2.2 MB',
    pages: null,
    fileDate: '2 April 2026',
  },
  {
    slug: 'pet-policy',
    size: '49 KB',
    pages: 1,
    fileDate: '20 February 2026',
  },
  {
    slug: 'video-surveillance-policy',
    size: '32 KB',
    pages: 1,
    fileDate: '20 February 2026',
  },
];

export const metaFor = (slug: string): DocMeta | undefined =>
  docMeta.find((d) => d.slug === slug);
